language: python

python:
  #- 2.7
  #- 3.5
  - 3.6

install:
  - pip install -r requirements/dev.txt
  - pip install codecov
  - pip install python-owasp-zap-v2.4

script:
  - python -m unittest discover
  - behave
  - coverage erase
  - coverage run test_webapp.py && coverage html
  #  pylint --output-format=text webapp.py

after_success:
  - codecov

notifications:
  slack: f5devops:CrAlC3U8CJDvcUi8RvWH0QRk
